CREATE TABLE item (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    deskripsi VARCHAR NOT NULL,
    qty INTEGER NOT NULL,
    harga DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
